Beaver Builder Cards Enhancement
brainstormforce/bb-bootstrap-cards pull request #9
Opened 2017-03-17 11:30 UTC by bhushanb20

- Change: Old: Beaver Builder Bootstrap Cards | New: Beaver Builder Cards
- Update: Added image alt tag.
- Card image source enhancement: Media / URL.
- Update: Textarea to Text Editor for more flexibility.
- Fixed: PHP Notice Errors.

2017-03-21 06:06 UTC, Nikschavan requested changes

2017-03-21 06:06 UTC, Nikschavan commented on bb-bootstrap-cards-module/bb-bootstrap-cards-module.php
> +                                'url'           => __('URL', 'fl-builder')
Check the correct text-domain

2017-03-21 06:06 UTC, Nikschavan commented on bb-bootstrap-cards-module/bb-bootstrap-cards-module.php
> +                            'placeholder'   => __( 'http://www.example.com/my-photo.jpg', 'fl-builder' )
Check the text-domain

2017-03-21 06:06 UTC, Nikschavan commented
@bhushanb20 The PHPCS requirements are also required to be fixed before we merge this.

2017-03-21 10:12 UTC, bhushanb20 commented on bb-bootstrap-cards-module/bb-bootstrap-cards-module.php
> +                                'url'           => __('URL', 'fl-builder')
I have updated text domain to "bb-bootstrap-cards"

2017-03-21 10:13 UTC, bhushanb20 commented on bb-bootstrap-cards-module/bb-bootstrap-cards-module.php
> +                            'placeholder'   => __( 'http://www.example.com/my-photo.jpg', 'fl-builder' )
I have updated text domain to "bb-bootstrap-cards"

2017-04-10 05:19 UTC, Nikschavan approved these changes

2017-04-10 05:20 UTC, merged